---
- name: setup tls 1.2
  win_regedit:
      path: HKLM:\Software\Microsoft\.NETFramework\v4.0.30319
      name: SchUseStrongCrypto
      data: 1
      type: dword

- win_regedit:
      path: HKLM:\Software\Wow6432Node\Microsoft\.NETFramework\v4.0.30319
      name: SchUseStrongCrypto
      data: 1
      type: dword

- name: Check NuGet Package provider is installed
  win_stat:
      path: C:\Program Files\PackageManagement\ProviderAssemblies\nuget
  register: nuget

- name: Ensure NuGet Package provider is installed
  win_shell: >
      Find-PackageProvider -Name Nuget -ForceBootstrap
      -IncludeDependencies
  when:
      - ansible_powershell_version == 5
      - nuget.stat.exists == false
