---

# - hosts: rootca
  # vars_files: vars.yml
  # roles:
    # - {role: upgrade_wmf51, when: ansible_powershell_version == 4}
    # - pwsh_gallery
    # - win_rootca

- hosts: subca
  vars_files: vars.yml
  roles:
    - dc_dns
    - join_domain
    - {role: upgrade_wmf51, when: ansible_powershell_version == 4}
    - pwsh_gallery
    - win_subca
