---
- hosts: dc
  vars_files: vars.yml
  roles:
    - {role: upgrade_wmf51, when: ansible_powershell_version == 4}
    - pwsh_gallery
  tasks:
    - name: Ensure AD Domain Services is installed
      win_feature:
        name: AD-Domain-Services
        state: present
        include_sub_features: true
        include_management_tools: true
      async: 900
      poll: 120

    - name: Create a new domain in a new forest
      win_domain:
        dns_domain_name: "{{ domain }}"
        safe_mode_password: password123!
        create_dns_delegation: no
      register: domain_install

    - include_role:
        name: dc_dns

    - name: Reboot after DC install
      when: domain_install.reboot_required == true
      win_reboot:

    - name: wait for services to start up
      ansible.windows.win_service_info:
        name: DNS
      register: dns_started
      until:
        - dns_started.services[0].process_id is defined
        - dns_started.services[0].process_id != ""
      retries: 10

    - name: Create SQL SVC Account
      win_domain_user:
        name: svc_sql
        firstname: SQL
        surname: ServiceAccount
        upn: svc_sql@{{ domain }}
        password: B0bP4ssw0rd
        password_never_expires: true
        state: present

