---
- hosts: sccm
  vars_files: vars.yml
  roles:
    - dc_dns
    - join_domain
    - {role: upgrade_wmf51, when: ansible_powershell_version == 4}
    - role: sql_server
      vars:
        source: \\192.168.33.1\vagrant\LabSources\SQL
        username: vagrant
        password: vagrant
    - role: sccm
      vars:
        source: \\192.168.33.1\vagrant\LabSources\SCCM
        username: vagrant
        password: vagrant
