---
- name: Upload public key
  win_copy:
    src: files/app.{{ domain }}.cer
    dest: C:\ansible\
- name: Import trusted CA
  win_certificate_store:
    path: C:\ansible\app.{{ domain }}.cer
    state: present
    store_name: AuthRoot
